"use client";

export function NarrativeReport({ narrative, loading }: { narrative: string | null; loading: boolean }) {
  if (loading) {
    return (
      <div className="panel report-card">
        <div className="meta"><span className="spinner" />Agent is narrating the trace…</div>
      </div>
    );
  }
  if (!narrative) return null;

  return (
    <div className="panel report-card">
      <div className="report-header">
        <div className="report-title">Investigation narrative</div>
        <div className="report-timestamp">generated by agent</div>
      </div>
      <div className="narrative">{narrative}</div>
    </div>
  );
}
